import Login from "@/components/Login";
import Cookies from "js-cookie";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { useState, useEffect } from "react";

export default function Home() {
  const Images = [
    "https://www.instagram.com/images/instagram/xig/homepage/screenshots/screenshot1.png?__d=www",
    "https://www.instagram.com/images/instagram/xig/homepage/screenshots/screenshot2.png?__d=www",
    "https://www.instagram.com/images/instagram/xig/homepage/screenshots/screenshot3.png?__d=www",
    "https://www.instagram.com/images/instagram/xig/homepage/screenshots/screenshot4.png?__d=www",
  ];
  const [count, setCount] = useState(0);
  const router = useRouter();
  const token = Cookies.get("token");

  //slideshow
  useEffect(() => {
    const interval = setInterval(() => {
      setCount((prev) => (prev == Images.length - 1 ? (prev = 0) : prev + 1));
    }, 4000);
    return () => clearInterval(interval);
  }, []);

  useEffect(() => {
    if (token) {
      router.push("/anasayfa");
    }
  }, [token]);

  return (
    <>
      <Head>
        <title>Instagram</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/instaFavicon.png" />
      </Head>
      <div className="h-screen bg-gray-50 w-full flex items-center justify-center">
        <div className="flex items-center justify-center">
          <div className="relative hidden md:block">
            <Image
              width={450}
              height={600}
              src="https://www.instagram.com/images/instagram/xig/homepage/phones/home-phones.png?__makehaste_cache_breaker=HOgRclNOosk"
              alt="instaImage"
            />
            <Image
              width={240}
              height={100}
              src={Images[count]}
              alt="instaImage1"
              className={`image absolute top-7 right-[58px] transition-opacity duration-400`}
            />
          </div>
          <Login />
        </div>
      </div>
    </>
  );
}
